- file:
    path: tests/hermesBridge/scenario01.properties
    change:
        - insert: 2
          highlight: true
          snippet: scenario01Complete
- file:
    path: tests/hermesBridge/scenario01/conscienceAddress.xml
    change: add
- file:
    path: tests/hermesBridge/scenario01/hermesAddress.xml
    change: add
- snippet:
    name: scenario01Complete
    markup: none
    context: 50
    