- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
      - insert: 1
        snippet: updateConfiguration
      - insert: 1
        snippet: updateConfiguration
- file:
    path: configurations/NewHorizons/BuildInfo.properties
    change:
      - old: 2
        new: 2
        snippet: updateBuildInfo
- file:
    path: configurations/NewHorizons/ConfigurationCheckExpiration.xml
    change: add
- file:
    path: configurations/NewHorizons/ConfigurationProcessDestination.xml
    change:
      - old: 1
        new: 1
        snippet: updateConfigurationProcessDestination
      - old: 1
        new: 1
        snippet: updateConfigurationProcessDestination
- file:
    path: configurations/NewHorizons/DatabaseChangelog.xml
    change:
      - insert: 15
        snippet: updateDatabaseChangelog
- snippet:
    name: updateConfiguration
    markup: xml
    context: 1000
- snippet:
    name: updateConfigurationProcessDestination
    markup: xml
    context: 1000
- snippet:
    name: updateDatabaseChangelog
    markup: xml
    context: 1000
- snippet:
    name: updateBuildInfo
    markup: xml
    context: 1000
    