- file:
    path: tests/hermesBridge/common.properties
    change:
        - insert: 3
          highlight: true
          snippet: completeCommonProperties
- snippet:
    name: completeCommonProperties
    markup: none
    context: 50
