- file:
    path: tests/NewHorizons/common.properties
    change: add
- file:
    path: tests/NewHorizons/scenario01.properties
    change: add
- file:
    path: tests/NewHorizons/scenario01/expectedErrorMsg.txt
    change: add
- file:
    path: tests/NewHorizons/scenario01/invalidBookingNoDestinations.xml
    change: add
- file:
    path: tests/NewHorizons/scenario01/nonsense.txt
    change: add
- file:
    path: tests/NewHorizons/scenario01/validBooking.xml
    change: add
- file:
    path: tests/NewHorizons/scenario01/validBooking2Dest.xml
    change: add
- file:
    path: configurations/NewHorizons/ConfigurationCheckBooking.xml
    change: add
- file:
    path: configurations/NewHorizons/Configuration.xml
    change:
        - insert: 1
          highlight: true
          snippet: addCheckBookingAdapter
        - insert: 1
          highlight: true
          snippet: addCheckBookingAdapter
- file:
    path: configurations/NewHorizons/StageSpecifics_LOC.properties
    change:
        - insert: 1
          snippet: dummySetStub4testtool
- snippet:
    name: addCheckBookingAdapter
    markup: xml
    context: 50
- snippet:
    name: dummySetStub4testtool
    markup: none
    context: 50