- file:
    path: configurations/ladybug/Configuration.xml
    change:
        - old: 1
          new: 1
          highlight: true
          snippet: referenceExternalTime
- snippet:
    name: referenceExternalTime
    markup: xml
    context: 100
