- file:
    path: configurations/NewHorizons/ConfigurationIngestBooking.xml
    change:
        - old: 1
          new: 1
          highlight: true
          snippet: addForEachChildElementPipe
        - insert: 7
          highlight: true
          snippet: addForEachChildElementPipe
- snippet:
    name: addForEachChildElementPipe
    markup: xml
    context: 5